<?php $items = $block->getNews(); ?>

<style>
 .card-news {
	 border: none;
}
 .card-img {
	 border-radius: 0;
}
 .vgr-cards .card-news {
	 display: flex;
	 flex-flow: wrap;
	 flex: 100%;
	 margin-bottom: 40px;
}
 .vgr-cards .card:nth-child(even) .card-img-body {
	 order: 2;
}
 .vgr-cards .card:nth-child(even) .card-body {
	 padding-left: 0;
	 padding-right: 1.25rem;
}
 @media (max-width: 576px) {
	 .vgr-cards .card {
		 display: block;
	}
}
 .vgr-cards .card-img-body {
	 flex: 1;
	 overflow: hidden;
	 position: relative;
}
 @media (max-width: 576px) {
	 .vgr-cards .card-img-body {
		 width: 100%;
		 height: 200px;
		 margin-bottom: 20px;
	}
}
 .vgr-cards .card-img {
	 width: 100%;
	 height: auto;
	 position: absolute;
	 margin-left: 50%;
	 transform: translateX(-50%);
}
 @media (max-width: 1140px) {
	 .vgr-cards .card-img {
		 margin: 0;
		 transform: none;
		 width: 100%;
		 height: auto;
	}
}
 .vgr-cards .card-body {
	 flex: 2;
	 padding: 0 0 0 1.25rem;
}
 @media (max-width: 576px) {
	 .vgr-cards .card-body {
		 padding: 0;
	}
}
 
</style>

<?php if (!empty($items)): ?>
    <div class="container mt-5">
        <h2 class="text-center mb-5"><?= $block->escapeHtml(__('Tin tức hôm nay')) ?></h2>
        <div class="row">
            <?php foreach ($items as $item): ?>
                    <div class="card-group vgr-cards">
                      <div class="card-news">
                        <div class="card-img-body">
                        <img class="card-img" src=<?= $item['img'] ?> alt="Card image cap">
                        </div>
                        <div class="card-body">
                          <h4 class="card-title"><?= $item['title'] ?></h4>
                          <p class="card-text"><?= $item['des'] ?></p>
                          <a href="<?= $item['link']?>" class="btn btn-outline-primary" target="_blank">Read more</a>
                        </div>
                      </div>
                    </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php else: ?>
    <p>No news items found.</p>
<?php endif; ?>